services:
  postgres:
    container_name: pg_container_for_booking
    image: postgres:14
    command:
      - "postgres"
      - "-c"
#      - "config_file=/etc/postgresql.conf"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    environment:
      POSTGRES_DB: "booking"
      POSTGRES_USER: "bookinguser"
      POSTGRES_PASSWORD: "pg4booking"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./init_sql/:/docker-entrypoint-initdb.d
      - ./booking-data:/var/lib/postgresql/data
#      - ./postgresql.conf:/etc/postgresql.conf:ro
    ports:
      - "6432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U bookinguser -d booking" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 4G
    networks:
      - postgres

  postgres_exporter:
    container_name: exporter_container_for_booking
    image: prometheuscommunity/postgres-exporter:v0.10.1
    environment:
      DATA_SOURCE_URI: "postgres:5432/booking?sslmode=disable"
      DATA_SOURCE_USER: "bookinguser"
      DATA_SOURCE_PASS: "pg4booking"
      PG_EXPORTER_EXTEND_QUERY_PATH: "/etc/postgres_exporter/queries.yaml"
    volumes:
      - ./queries.yaml:/etc/postgres_exporter/queries.yaml:ro
    ports:
      - "9188:9187"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 500M
    networks:
      - postgres

volumes:
  booking-data:

networks:
  postgres:
    driver: bridge

